### ISSUE TITLE
Incorrect hole sizes

### ISSUE THREAD

**Issue by brett932** [JustinOng/Altium-Library-Compute-Module-3#1]
Hi Justin,
I noticed and error in the 1473005-4 footprint contained in 1473005-4.PcbLib
Both holes are of incorrect diameter 1.2mm.
The hole located @ (0mm,        0mm) should be 1.6mm
The hole located @ (-66.8mm,  0mm) should be 1.1mm
I am working in reference to TE's [datasheet](http://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1473005&DocType=Customer+Drawing&DocLang=English)

Cheers,
Brett Hill

**Comment by JustinOng** [comment]
Thank you for the feedback! I have corrected the hole sizes. In addition, I've also removed the pad around the holes as I realised plastic pins go into the holes and can't be soldered.
