### ISSUE TITLE
issue with footprint

### ISSUE THREAD

**Issue by jamess0stricklandlabs** [JustinOng/Altium-Library-Compute-Module-3#2]
P
[1473005-4 -edit.zip](https://github.com/JustinOng/Altium-Library-Compute-Module-3/files/2309138/1473005-4.-edit.zip)

ins 1 through to 200 are in the wrong position. otherwise it looks fine. to fix, select  the pin rows and set to y= 3.6 & -3.6

i would also recommend setting the other mounting pads to say 201 and making a 0V/GND connection

**Comment by JustinOng** [comment]
Thank you for the feedback.

I'm not sure about the spacing between the top and bottom rows of the pads however - according to the drawings [here](http://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1473005&DocType=Customer+Drawing&DocLang=English), the y spacing of each row of pads should be 3.1 + 1 + 1 = 5.1mm? May I ask how did you arrive at 3.6 + 3.6 = 7.2mm? The following screenshot is from page 2 of the linked drawing. ![capture](https://user-images.githubusercontent.com/9336475/44448325-83c83a80-a61d-11e8-8172-00d5657322a1.PNG)

>i would also recommend setting the other mounting pads to say 201 and making a 0V/GND connection

Thats a good point. I'll expose the two mounting pads on the Part A.

**Comment by jamess0stricklandlabs** [comment]
Hi Justin,

altium pin positions are based on the center of the pin. sorry 4.1, 3.1mm +
half the length of the pin, 1mm so 4.1mm   so you should have 4,1 & -4.1,
for some reason i halved 2mm to 1mm then halved it again :P

also another good trick for designing footprints in altuim designer is to
find and add the 3d step image. that's how i picked up the error in the
footprint. :) - see attached, i corrected the spacing

another trick is to print out the datasheet and write the notes. also
thanks for the footprint :D




kind regards,

James Strickland

**Comment by JustinOng** [comment]
Ah. I see where I went wrong. I didn't know that the heavy dot represented an arrow head. Thanks, will correct the footprint accordingly.
